### PR TITLE
Add disclaimer component & display on every page

### PR DESCRIPTION
**Pull request by jmcook1186**
The incubation disclaimer should be displayed on every website page. Docusaurus has an `announcementBanner` component but it does not appear to be resizeable and the disclaimer is too long to fit in the default box, so I created a new component with the desired styling and added to each page.

### CODE REVIEW

**Review by osamajandali — CHANGES_REQUESTED** [review]
Hey @jmcook1186 , Thanks for your work in here
But this should not be done like this for two reasons:
- It's not practical that you need to add the disclaimer component everytime you add new page
- The disclaimer is under each page title, which is not best place to put an alert
Take a look on [this line ](https://github.com/Green-Software-Foundation/sci-guide/blob/5f63d846838fbbeff858c51afb234126d781ef81/src/theme/Navbar/index.js#L7) from another project, where I implemented a disclaimer.
You need to eject first the component and the add the line you want. I can do it very quickly unless you want to take care of it

**Comment by jmcook1186** [comment]
@osamajandali ok - thanks, yes if you can do it quickly, please go ahead.

**Comment by osamajandali** [comment]
I add the disclaimer to the site. Check it out @jmcook1186.

**Comment by Sophietn** [comment]
Thanks @osamajandali - it looks great

**Pull request closed without merging**
